### ISSUE TITLE
Extension - Questions about Open new tab, Do not disturb.

### ISSUE THREAD

**Issue by maxdevjs** [dailydotdev/daily-apps#150]
Hello.

The service is amazing, but I have a couple curiosities:

- when active, the extension overrides the new tab. There is a way to set a different behaviour (for examples, to open content only when clicking on the icon, not changing the user new tab behaviour)?

- in `Do not disturb` mode, every new tab is redirected to a specific page. There is a way to set a different behaviour?

Thank you.

**Comment by idoshamun** [comment]
Hey @maxdevjs,

Sorry for the late response.

* Unforutantely, there is no way to set a different behavior 🤷‍♂️
* The "Do Not Disturb" mode redirects to Chrome's default new tab page. This cannot be changed currently.

**Comment by maxdevjs** [comment]
Thank you for the reply. Great AMA!
