### ISSUE TITLE
Scroll to top not happening when user selects another source from My Public Sources

### ISSUE THREAD

**Issue by Ravindra-FED** [dailydotdev/daily-apps#152]
If the user scroll's down in the page and selects another source, the page is not getting scrolled to top to show the latest blogs of that resource

**Comment by sshanzel** [comment]
I think we can set a hotkey for `scrollToTop`?

**Comment by Ravindra-FED** [comment]
Correct me if i am wrong, are you saying some button to the user to select to scrollToTop? 
It might require a Visual Design how the button should appear
or we can directly take the user to top after selecting any option in the side nav.

**Comment by sshanzel** [comment]
Daily.dev actually have a feature where you can navigate the feed through your keyboard. I suggest it be enhanced to add `scrollToTop` when pressing `t` or something.

**Comment by sshanzel** [comment]
Or that kind of button could work as well.

**Comment by Ravindra-FED** [comment]
I am not able to replicate this issue now, is there any recent push for this fix?

**Comment by idoshamun** [comment]
Hey @Ravindra-FED,
Sorry for the late response, I somehow missed the notification about this.
I didn't push any fix but maybe with the recent redesign, we fixed it by coincidence.
Could you please verify the current status of this issue?

**Comment by Ravindra-FED** [comment]
Hi @idoshamun , the issue is fixed now. Thanks

**Comment by idoshamun** [comment]
Woohoo! Glad to hear :)
