### ISSUE TITLE
Need for firefox android ❣️

### ISSUE THREAD

**Issue by mrcodekiddie** [dailydotdev/daily-apps#169]
![images (4).jpg](https://user-images.githubusercontent.com/24442168/95495423-0a3a6480-09bd-11eb-82b5-bc86bb9a0940.jpg)
Android Firefox ku ungoppanada kuduppan

**Comment by idoshamun** [comment]
Hey! Unfortunately, at the moment this is out of our product scope.
Stay tuned as we're working on a web version.
