### ISSUE TITLE
Feat: Ability to save preferred article sort-by between tabs

### ISSUE THREAD

**Issue by thinkverse** [dailydotdev/daily-apps#230]
Hello there. 👋

I have a feature idea I'd like to run by the contributors. Namely the ability to save which `sort-by` should be used between tab sessions. As it stands currently the `popular` sort is used whenever a new tab is opened. I would like to have the option to toggle `save article sort-by` and the latest `sort-by` I've used will be saved until that option is unchecked again.

This way I can set my sort to `recent` and that sort will be used until the time I have unchecked the `save article sort-by` option and then `popular` sort will be the default again. I hope I explained that well enough. 🤔

I came to the option of suggesting the check version to make the saving of the `sort-by` an opt-in. Instead of modifying the current behavior of the `sort-by` functionality and potentially creating back-lash from current users.

Any input would be appreciated. 😀

## Screenshot of potential implementation.

![Screen Shot 2020-11-18 at 12 42 05 AM](https://user-images.githubusercontent.com/2221746/99463838-f0365f00-2936-11eb-9571-7cbeb02976df.png)

**Comment by thinkverse** [comment]
This may be the wrong repo to suggest features in. Not sure, so I'm leaving this open until I've been told otherwise. 👍

**Comment by idoshamun** [comment]
Hey @thinkverse,

Glad to talk to you again and see you active here 🙌
The primary repo for issues is https://github.com/dailydotdev/daily but here is perfectly fine as well.

I believe many users can relate to saving the last visited feed as the default one.
I think we can accept this behavior as a default behavior. 
I'm not sure a setting is necessary as it's more simple to just change the feed than accessing your personal settings.

What do you think?

**Comment by thinkverse** [comment]
That's how I thought it worked from the beginning. That the last selected `sort-by` would stick upon opening a new tab. But it resets to `popular` every time.

True, changing the feed would be the simpler option. The setting version was designed to be an opt-in route to saving the `sort-by`. As an opt-in would be less intrusive than changing how the current feed works. Sure, more complicated as it would need to rely on the state of the setting before saving the `sort-by`, but this way it's completely up to the end-user to decide if they want to save it.

**Comment by thinkverse** [comment]
And I wasn't supposed to click that button. 😂&nbsp; Haha.

As I was going to keep writing; I guess the simpler version of changing the feed would be the best option. I'm just thinking of the end-user. Wouldn't want to introduce a feature that breaks their already established flow.

**Comment by idoshamun** [comment]
I'll proceed with the simpler version, I find it better in many aspects.
Not many people open the settings panel so some might want this feature and will never discover it.
I'll release it today probably.

**Comment by thinkverse** [comment]
Now that's a quick turn-around damn. 😮 &nbsp; Much appreciated feature. Thank you for your hard work and dedication to the developer community. 🔥

**Comment by idoshamun** [comment]
Here's the real turn-around, it's already available in version 2.24.1.
Make sure to update 🚀

Thank you for the kind words, this keeps us motivated to keep going 🙏
