### ISSUE TITLE
vertical nav bar issue

### ISSUE THREAD

**Issue by AM-77** [dailydotdev/daily-apps#27]
When resizing the window and scrolling vertically the numbers scroll with the reset of the page but the nav bar doesn't. 
The numbers should be fixed inside the nav bar, or the nav bar should scroll with the whole page.

![Screenshot from 2019-08-15 18-50-57](https://user-images.githubusercontent.com/18232579/63111935-285e2d80-bf8f-11e9-9679-62e0317e62f1.png)
![Screenshot from 2019-08-15 18-59-14](https://user-images.githubusercontent.com/18232579/63111938-2a27f100-bf8f-11e9-83ab-96b3ddf60f69.png)

**Comment by idoshamun** [comment]
@AM-77 thank you for the contribution and reporting this bug :)
If you are up to the challenge, we would love to get your contribution on this one

**Comment by saqibameen** [comment]
@idoshamun if this hasn't been resolved yet, I would love to contribute on this one.

**Comment by idoshamun** [comment]
@saqibameen thank you! I would be great :)

**Comment by saqibameen** [comment]
Awesome! So, which way would you like me to proceed? Should we fix the sidebar or navbar?

**Comment by idoshamun** [comment]
Sidebar, please.
I also noticed that in all screen sizes the numbers in the side don't update.

**Comment by saqibameen** [comment]
Sure. I was about to ask. In my secondary screen it is constant to 48 I guess and then it's blank. So, I believe fixing it will be a good idea.

**Comment by saqibameen** [comment]
I changed the position from `absolute` to `fixed` so it is fixed w.r.t the viewport and doesn't change on a scroll. But it leaves the space on top empty. How does it look to you? 

I believe we need some sort of event handler so it gets a negative margin every time it's not in the default position. What do you say? If yes, what would it look like?

Take a look at the GIF. 

![PR GIF](https://i.imgur.com/y3Rq6Ay.gif)

**Comment by idoshamun** [comment]
Actually it was once worked perfectly fine. The expected behavior is that you will have the numbers keep running. This is why it should be `absolute`. I believe something messed up here:
https://github.com/dailydotdev/daily-apps/blob/master/packages/extension/src/routes/Home.vue#L208 due to changes in the dom structure of previous commits. Basically, I'm trying to calculate there how many numbers can be filled vertically and then actually adding them to the sidebar. Maybe you should dive there and try to see what changed and fix it. Or maybe it doesn't call this function anymore when the feed is updated.

**Comment by saqibameen** [comment]
@idoshamun thank you for the input. So, I tried to debug found out that the function `updateLines()` is not being called when the feed is updated. 

It was supposed to be called under a watcher named `posts()`. 

https://github.com/dailydotdev/daily-apps/blob/15bce771fb0c6f71bc94ba699a6746362e270c0c/packages/extension/src/routes/Home.vue#L448-L451

I could not find any `posts` data. I looked into the commit history and found out that you probably created a `Feed` component and encapsulated `posts` into that. Or changed the store according to that. 

If I change `posts()` to `feed()` in the watchers, and it works fine:
https://github.com/dailydotdev/daily-apps/blob/15bce771fb0c6f71bc94ba699a6746362e270c0c/packages/extension/src/routes/Home.vue#L448-L451

Here is the commit where `posts` is being removed from the `DaHome.vue` component.

https://github.com/dailydotdev/daily-apps/commit/8e3dca5b2984f33e791bf3157c058766c74252fd#diff-28147bdc2c22676eb273ca31213a595eL409

Let me know if I'm approaching it the right way, I'll go ahead and create a PR.

**Comment by idoshamun** [comment]
I believe you nailed it! You managed to go back in the git history and understand my deeds :boom: 
Let's create a test to cover this case so it won't happen again, what do you think?

**Comment by saqibameen** [comment]
Sure, can you please guide me about the tests in Daily and how'd this test look like?

**Comment by idoshamun** [comment]
Your new test should be placed here:
https://github.com/dailydotdev/daily-apps/blob/master/packages/extension/__tests__/Home.js
You can find there references for tests of the `Home` page.
I believe your test should check that more line numbers are added when more content is added to the feed. Does it make sense to you?

**Comment by saqibameen** [comment]
Yeah, it totally makes sense. I'll take a look at it and get back.

**Comment by saqibameen** [comment]
I have spent quite some time on this test. I'm not well versed in testing, so tried to make sense of the existing tests. Below is what I understood, let me know if I am headed in the right direction. 

- Currently, the` posts` array is empty in the state. So, the feed is not being rendered. 
- We'd probably first need to add some items to the `posts` array in the `state`. Then add some more items OR try to somehow trigger the `fetchNextFeedPage()`. 

What I am understanding is, we need to somehow trigger `fetchNextFeedPage()` method which is triggered on the scroll. I am not sure in testing if we need to provide its implementation in Store or how that's going to work?

**Comment by idoshamun** [comment]
Actually `updateLines` is called upon any change to the `posts` object in the store. You don't have to actually call `fetchNextFeedPage` but rather add more posts. Once the `posts` object changes the `updateLines` will be called.

**Comment by saqibameen** [comment]
@idoshamun I have created PR where this issue is fixed. Let's collaborate there and move forward to add test and complete this.

**Comment by idoshamun** [comment]
No longer relevant as we updated the design. Thanks for everything :)
