### ISSUE TITLE
Auto refresh to show new posts

### ISSUE THREAD

**Issue by mojtabakaviani** [dailydotdev/daily-apps#319]
Usually have new tab to see posts but not auto refresh at now if new posts released until manually refresh page. Can add mechanism to showing new posts real time or every few minutes.

**Comment by idoshamun** [comment]
Hi @mojtabakaviani,

Thanks for the idea 🙏
Your idea is currently out of scope as the feed usually doesn't update so often so a quick manual refresh should do it.
In the future, we might consider it again.
