### ISSUE TITLE
Add filter to remove read articles

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily-apps#99]
Originating from a feature request (https://github.com/dailydotdev/daily/issues/142) and following the completion of the server-side implementation (https://github.com/dailydotdev/daily-api/issues/46), we need to add the extension implementation.

Regarding the user interface, we would like to add a new switch in the preferences section. The new switch should create a new column to the right of the existing preferences switches. It should be labeled with "Hide read posts" and should be turned off by default. The new column should be `32px` pixels apart from the existing one.
![image](https://user-images.githubusercontent.com/1993245/79685829-4f6aae80-8244-11ea-8e42-d822a42d7ca0.png)

As long as it is turned off no changes should occur to the existing feed and once it is turned on,  the read articles should be removed **only from the main feed**. It shouldn't affect the bookmarks, single-source/tag, search and all the other feeds.

**Comment by prateek3255** [comment]
I will start working on it soon enough.
